project:
  type: book
  output-dir: docs

book:
  title: "Ben Koshy Stat 468 Final Project"
  author: "Ben Koshy"
  date: "2025-08-11"
  chapters:
    - index.qmd
    - Question.qmd
    - Data import.qmd
    - Tidy.qmd
    - Visualize.qmd
    - Model.qmd
    - Communicate.qmd
    - References.qmd

bibliography: references.bib
  
execute:
  freeze: auto
  
format:
  html:
    theme: cosmo
    code-fold: true
editor: visual

